import {
  FaReact, FaNodeJs, FaCss3Alt, FaHtml5, FaJs
} from "react-icons/fa";
import {
  SiNextdotjs, SiTailwindcss, SiMongodb, SiPostgresql, SiTypescript, SiExpress, SiNestjs, SiSwagger, SiTypeorm
} from "react-icons/si";

export const technologies = [
  {
    id: 1,
    name: "React",
    type: "framework",
    description: "React",
    url: "https://react.dev/",
    image: "https://i.imgur.com/pJqSsPz.png",
    icon: FaReact,
  },
  {
    id: 2,
    name: "Next.js",
    type: "framework",
    description: "Nextjs",
    url: "https://nextjs.org/docs",
    image: "https://i.imgur.com/jye2QBg.png",
    icon: SiNextdotjs,
  },
  {
    id: 3,
    name: "Tailwind CSS",
    type: "framework",
    description: "Tailwind_CSS",
    url: "https://tailwindcss.com/",
    image: "https://i.imgur.com/LoXN25Y.png",
    icon: SiTailwindcss,
  },
  {
    id: 4,
    name: "JavaScript",
    type: "language",
    description: "JavaScript",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    image: "https://cdn.worldvectorlogo.com/logos/javascript-1.svg",
    icon: FaJs,
  },
  {
    id: 5,
    name: "TypeScript",
    type: "language",
    description: "TypeScript",
    url: "https://www.typescriptlang.org/docs/",
    image: "https://cdn.worldvectorlogo.com/logos/typescript.svg",
    icon: SiTypescript,
  },
  {
    id: 6,
    name: "CSS",
    type: "language",
    description: "CSS",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    image: "https://cdn.worldvectorlogo.com/logos/css-3.svg",
    icon: FaCss3Alt,
  },
  {
    id: 7,
    name: "HTML",
    type: "language",
    description: "HTML",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    image: "https://cdn.worldvectorlogo.com/logos/html-1.svg",
    icon: FaHtml5,
  },
  {
    id: 8,
    name: "Node.js",
    type: "runtime",
    description: "Nodejs",
    url: "https://nodejs.org/docs/latest/api/",
    image: "https://i.imgur.com/JPOxfsV.png",
    icon: FaNodeJs,
  },
  {
    id: 9,
    name: "Express.js",
    type: "framework",
    description: "Expressjs",
    url: "https://expressjs.com/",
    image: "https://i.imgur.com/UTOE0l5.png",
    icon: SiExpress,
  },
  {
    id: 10,
    name: "MongoDB",
    type: "database",
    description: "MongoDB",
    url: "https://www.mongodb.com/",
    image: "https://i.imgur.com/ZUhhQU6.png",
    icon: SiMongodb,
  },
  {
    id: 11,
    name: "PostgreSQL",
    type: "database",
    description: "PostgreSQL",
    url: "https://www.postgresql.org/",
    image: "https://i.imgur.com/5oZ5kNv.png",
    icon: SiPostgresql,
  },
  {
    id: 12,
    name: "Nest.js",
    type: "framework",
    description: "Nestjs",
    url: "https://nestjs.com/",
    image: "https://i.imgur.com/2PnHEjT.png",
    icon: SiNestjs,
  },
  {
    id: 13,
    name: "Swagger",
    type: "runtime",
    description: "Swagger",
    url: "https://swagger.io/",
    image: "https://i.imgur.com/placeholder.png",
    icon: SiSwagger,
  },
  {
    id: 14,
    name: "TypeORM",
    type: "database",
    description: "TypeORM",
    url: "https://typeorm.io/",
    image: "https://i.imgur.com/placeholder.png",
    icon: SiTypeorm,
  },
];