export const technologies = [
  {
    id: 1,
    name: "React",
    type: "framework",
    description: "React",
    url: "https://es.wikipedia.org/wiki/React",
    image: "https://i.imgur.com/pJqSsPz.png",
  },
  {
    id: 2,
    name: "Next.js",
    type: "framework",
    description: "Nextjs",
    url: "https://es.wikipedia.org/wiki/Next.js",
    image: "https://i.imgur.com/jye2QBg.png",
  },
  {
    id: 3,
    name: "Tailwind CSS",
    type: "framework",
    description: "Tailwind_CSS",
    url: "https://es.wikipedia.org/wiki/Tailwind_CSS",
    image: "https://i.imgur.com/LoXN25Y.png",
  },
  {
    id: 4,
    name: "JavaScript",
    type: "language",
    description: "JavaScript",
    url: "https://es.wikipedia.org/wiki/JavaScript",
    image: "https://cdn.worldvectorlogo.com/logos/javascript-1.svg",
  },
  {
    id: 5,
    name: "TypeScript",
    type: "language",
    description: "TypeScript",
    url: "https://es.wikipedia.org/wiki/TypeScript",
    image: "https://cdn.worldvectorlogo.com/logos/typescript.svg",
  },
  {
    id: 6,
    name: "CSS",
    type: "language",
    description: "CSS",
    url: "https://es.wikipedia.org/wiki/CSS",
    image: "https://cdn.worldvectorlogo.com/logos/css-3.svg",
  },
  {
    id: 7,
    name: "HTML",
    type: "language",
    description: "HTML",
    url: "https://es.wikipedia.org/wiki/HTML",
    image: "https://cdn.worldvectorlogo.com/logos/html-1.svg",
  },
  {
    id: 8,
    name: "Node.js",
    type: "runtime",
    description: "Nodejs",
    url: "https://es.wikipedia.org/wiki/Node.js",
    image: "https://i.imgur.com/JPOxfsV.png",
  },
  {
    id: 9,
    name: "Express.js",
    type: "framework",
    description: "Expressjs",
    url: "https://es.wikipedia.org/wiki/Express.js",
    image: "https://i.imgur.com/UTOE0l5.png",
  },
  {
    id: 10,
    name: "MongoDB",
    type: "database",
    description: "MongoDB",
    url: "https://es.wikipedia.org/wiki/MongoDB",
    image: "https://i.imgur.com/ZUhhQU6.png",
  },
  {
    id: 11,
    name: "PostgreSQL",
    type: "database",
    description: "PostgreSQL",
    url: "https://es.wikipedia.org/wiki/PostgreSQL",
    image: "https://i.imgur.com/5oZ5kNv.png",
  },
];
