export const technologies = [
  {
    id: 1,
    name: "React",
    type: "framework",
    description: "React",
    url: "https://react.dev/",
    image: "https://i.imgur.com/pJqSsPz.png",
  },
  {
    id: 2,
    name: "Next.js",
    type: "framework",
    description: "Nextjs",
    url: "https://nextjs.org/docs",
    image: "https://i.imgur.com/jye2QBg.png",
  },
  {
    id: 3,
    name: "Tailwind CSS",
    type: "framework",
    description: "Tailwind_CSS",
    url: "https://tailwindcss.com/",
    image: "https://i.imgur.com/LoXN25Y.png",
  },
  {
    id: 4,
    name: "JavaScript",
    type: "language",
    description: "JavaScript",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    image: "https://cdn.worldvectorlogo.com/logos/javascript-1.svg",
  },
  {
    id: 5,
    name: "TypeScript",
    type: "language",
    description: "TypeScript",
    url: "https://www.typescriptlang.org/docs/",
    image: "https://cdn.worldvectorlogo.com/logos/typescript.svg",
  },
  {
    id: 6,
    name: "CSS",
    type: "language",
    description: "CSS",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    image: "https://cdn.worldvectorlogo.com/logos/css-3.svg",
  },
  {
    id: 7,
    name: "HTML",
    type: "language",
    description: "HTML",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    image: "https://cdn.worldvectorlogo.com/logos/html-1.svg",
  },
  {
    id: 8,
    name: "Node.js",
    type: "database",
    description: "Nodejs",
    url: "https://nodejs.org/docs/latest/api/",
    image: "https://i.imgur.com/JPOxfsV.png",
  },
  {
    id: 9,
    name: "Express.js",
    type: "framework",
    description: "Expressjs",
    url: "https://expressjs.com/",
    image: "https://i.imgur.com/UTOE0l5.png",
  },
  {
    id: 10,
    name: "MongoDB",
    type: "database",
    description: "MongoDB",
    url: "https://www.mongodb.com/",
    image: "https://i.imgur.com/ZUhhQU6.png",
  },
  {
    id: 11,
    name: "PostgreSQL",
    type: "database",
    description: "PostgreSQL",
    url: "https://www.postgresql.org/",
    image: "https://i.imgur.com/5oZ5kNv.png",
  },
];
