export const tecnologies = [
    {
      id: 1,
      name: "React",
      type: "framework",
      description: "React es un framework de JavaScript para construir interfaces de usuario de aplicaciones web y móviles.",
      url: "https://es.wikipedia.org/wiki/React",
      image: "https://i.imgur.com/pJqSsPz.png",
    },
    {
      id: 2,
      name: "Next.js",
      type: "framework",
      description: "Next.js es un framework de JavaScript para construir aplicaciones web y móviles rápidas y fáciles de desarrollar.",
      url: "https://es.wikipedia.org/wiki/Next.js",
      image: "https://i.imgur.com/jye2QBg.png",
    },
    {
      id: 3,
      name: "Tailwind CSS",
      type: "framework",
      description: "Tailwind CSS es un framework de CSS que proporciona herramientas para crear diseños de interfaces de usuario de alta calidad.",
      url: "https://es.wikipedia.org/wiki/Tailwind_CSS",
      image: "https://i.imgur.com/LoXN25Y.png",
    },
    {
        id: 4,
        name: "JavaScript",
        type: "language",
        description: "JavaScript es un lenguaje de programación interpretado que permite crear aplicaciones interactivas y dinámicas.",
        url: "https://es.wikipedia.org/wiki/JavaScript",
        image: "https://cdn.worldvectorlogo.com/logos/javascript-1.svg",
    },
    {
      id: 5,
      name: "TypeScript",
      type: "language",
      description: "TypeScript es un lenguaje de programación basado en JavaScript con tipado estático.",
      url: "https://es.wikipedia.org/wiki/TypeScript",
      image: "https://cdn.worldvectorlogo.com/logos/typescript.svg",
    },
    {
      id: 6,
      name: "CSS",
      type: "language",
      description: "CSS (Cascading Style Sheets) es un lenguaje de estilos para documentos web.",
      url: "https://es.wikipedia.org/wiki/CSS",
      image: "https://cdn.worldvectorlogo.com/logos/css-3.svg",
    },
    {
      id: 7,
      name: "HTML",
      type: "language",
      description: "HTML (HyperText Markup Language) es un lenguaje de marcado de páginas web.",
      url: "https://es.wikipedia.org/wiki/HTML",
      image: "https://cdn.worldvectorlogo.com/logos/html-1.svg",
    },
    {
      id: 8,
      name: "Node.js",
      type: "runtime",
      description: "Node.js es un entorno de ejecución de JavaScript en el servidor.",
      url: "https://es.wikipedia.org/wiki/Node.js",
      image: "https://i.imgur.com/JPOxfsV.png",
    },
    {
      id: 9,
      name: "Express.js",
      type: "framework",
      description: "Express.js es un framework de Node.js para crear aplicaciones web rápidas y escalables.",
      url: "https://es.wikipedia.org/wiki/Express.js",
      image: "https://i.imgur.com/UTOE0l5.png",
    },
    {
      id: 10,
      name: "MongoDB",
      type: "database",
      description: "MongoDB es una base de datos NoSQL orientada a documentos.",
      url: "https://es.wikipedia.org/wiki/MongoDB",
      image: "https://i.imgur.com/ZUhhQU6.png",
    },
    {
      id: 11,
      name: "PostgreSQL",
      type: "database",
      description: "PostgreSQL es una base de datos relacional escalable.",
      url: "https://es.wikipedia.org/wiki/PostgreSQL",
      image: "https://i.imgur.com/5oZ5kNv.png",
    },
  ];
  